### ISSUE TITLE
Data Modelling

### ISSUE THREAD

**Issue by sazankkdcool06** [onesubhadip/recipe-jungle#5]
Design & document data classes for post recipe use case

**Comment by sazankkdcool06** [comment]
**Recipe Data Model:**

{
    recipeId : "",
    authorId : "user_id"
    dishName : "some name",
    introduction: "",
    ingredients : [
        {
            item : {
                name: "item_name",
                category: ["vegetable,fruit,spice,meat,fish,dairy,others"]
            },
            quantity : "NUMg"
        }
    ],
    process: [
     { // Step
      stepnumber: "", 
      heading: "",
      subheading: "",
      details: "",
      images : [ "url-1", "url-2" ],
      substeps: [
            // array of steps
            // style will be different for sub steps
            ],
       estimated_time: ""
     },
     attributes: {
       tags : ["xxx","yyy"],
       difficultyLevel: "Easy/Medium/Hard"
       cuisine: ["Indian", "South Indian", "Mexican", "Italian", "North Indian", "Bengali"],
       category : "Veg/Non Veg",
       dishType : ["Soup/Salad/Appetizer/Bread/Snack/Main course/dessert/Beverages/Others"],
       mealTime : ["Breakfast/Lunch/Dinner/Snack/Brunch"]
     }

    ]
}

**Comment by onesubhadip** [comment]
Recipe:

```
{
    recipeId : "",
    authorId : "user_id"
   dishName : "some name",
    introduction: "",
   ingredients : [
       {
           item : {
               name: "item_name",
               category: ["vegetable,fruit,spice,meat,fish,dairy,others"]
           },
           quantity : "NUMg"
       }
   ],
    process: [
     { // Step
     stepnumber: "",
      heading: "",
      subheading: "",
      details: "",
      images : [ "url-1", "url-2" ],
      substeps: [
            // array of steps
            // style will be different for sub steps
            ],
     estimated_time: ""
     },
     attributes: {
      tags : ["xxx","yyy"],
     difficultyLevel: "Easy/Medium/Hard"
     cuisine: ["Indian", "South Indian", "Mexican", "Italian", "North Indian", "Bengali"],
      category : "Veg/Non Veg",
      dishType : ["Soup/Salad/Appetizer/Bread/Snack/Main course/dessert/Beverages/Others"],
    mealTime : ["Breakfast/Lunch/Dinner/Snack/Brunch"]
     }

    ]
}
```

**Comment by sazankkdcool06** [comment]
User:

```
{
     userId : "",
     firstName: "",
     lastName: "",
     email: "",
     age : "",
     country: "",
     city/region: "",
     hobbies: "",
     specialties: ["Indian", "South Indian", "Mexican", "Italian"],
     image :  ""
}
```
